theme: minima
title: Prasenjit's Technical Blog
author: Prasenjit Chakraborty
description: Compter Architecture and Performance Knowhow

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax


